---
title: "Govenor's challenge"
author: "Christian Lubin"
date: "25/10/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tseries); library(fUnitRoots);
GDP = read.csv("GDP.csv"); 
Inflation = read.csv("Inflation.csv"); 
Unemployment = read.csv("unemploymentRate.csv");

GDP = GDP[,1:2]; 
Inflation = Inflation[,1:2]; 
Unemployment = Unemployment[,1:3];

GDP.ts <- ts( GDP[,2] , start=c(1997,01) ,frequency = 12);
Inflation.ts <- ts(Inflation[,2], start = c(1990,01), frequency = 12);
Unemployment.ts <- ts(Unemployment[,2], start = c(1976,01), frequency = 12);
```

```{r}
par(mfrow=c(3,1));
plot(decompose(GDP.ts));
plot(decompose(Inflation.ts));
plot(decompose(Unemployment.ts))

GDP.random <-decompose(GDP.ts)$random;
Inflation.random <- decompose(Inflation.ts)$random;
Unemployment.random <- decompose(Unemployment.ts)$random

plot.ts(GDP.random);
plot.ts(Inflation.random);
plot.ts(Unemployment.random);

```
```{r}
#GDP
urkpssTest(GDP.ts, type = c("tau"), lags = c("short"),use.lag = NULL, doplot = TRUE)
GDP.ts.stationary = diff(GDP.ts, differences=1)
plot(GDP.ts.stationary)

#Inflation
urkpssTest(Inflation.ts, type = c("tau"), lags = c("short"),use.lag = NULL, doplot = TRUE)
Inflation.ts.stationary = diff(Inflation.ts, differences=1)
plot(Inflation.ts.stationary)
#Unemployment
urkpssTest(Unemployment.ts, type = c("tau"), lags = c("short"),use.lag = NULL, doplot = TRUE)
Unemployment.ts.stationary = diff(Unemployment.ts, differences=1)
plot(Unemployment.ts.stationary)
```

```{r}
#GDP - The ACF and PACF of the GDP.ts.stationary look better. The differencing method seemed to have 
#removed the nonstationary parts of the data better than the decompose function. I think using 
#GDP.ts.stationary to predict would be better. Looks like ARIMA(2,0,1)
par(mfrow=c(2,2));
acf(na.omit(GDP.random)); pacf(na.omit(GDP.random));
acf(na.omit(GDP.ts.stationary)); pacf(na.omit(GDP.ts.stationary));

#Inflation- None of the methods used seemed to have removed the non-stationary part of the data. 
#Other methods will be tried.Maybe (1,0,2)
par(mfrow=c(2,2));
acf(na.omit(Inflation.random)); pacf(na.omit(Inflation.random));
acf(na.omit(Inflation.ts.stationary)); pacf(na.omit(Inflation.ts.stationary));

#Unemployment - The ACF and PACF of the Unemployment.ts.stationary look better. The differencing 
#method seemed to have removed the nonstationary parts of the data better than the decompose 
#function. I think using Unemployment.ts.stationary to predict would be better. Looks like ARIMA(2,0,1)
par(mfrow=c(2,2));
acf(na.omit(Unemployment.random)); pacf(na.omit(Unemployment.random));
acf(na.omit(Unemployment.ts.stationary)); pacf(na.omit(Unemployment.ts.stationary));
```
```{r}
GDP.fit <- arima(GDP.ts.stationary,order = c(2,0,1)); Inflation.fit <- arima(Inflation.random,order = c(1,0,2)); Unemployment.fit <- arima(Unemployment.ts.stationary, order = c(2,0,1))

GDP.fit
Inflation.fit
Unemployment.fit
```

```{r}
GDP.predict <- predict(GDP.fit,n.ahead= 12);
Inflation.predict <- predict(Inflation.fit,n.ahead = 12);
Unemployment.predict <- predict(Unemployment.fit,n.ahead = 12);

GDP.pred.max <- GDP.predict$pred+GDP.predict$se;
GDP.pred.min <-GDP.predict$pred-GDP.predict$se;

Inflation.pred.max <- Inflation.predict$pred+Inflation.predict$se; 
Inflation.pred.min <-Inflation.predict$pred-Inflation.predict$se;

Unemployment.pred.max <- Unemployment.predict$pred+Unemployment.predict$se;
Unemployment.pred.min<-Unemployment.predict$pred-Unemployment.predict$se;
```

```{r}
#12 month prediction of each of the stationary parts of the 3 variables.
plot.ts(GDP.predict$pred,ylim=c(min(GDP.pred.min),max(GDP.pred.max)));
lines(GDP.pred.max,col="red");
lines(GDP.pred.min,col="red");

plot.ts(Inflation.predict$pred,ylim=c(min(Inflation.pred.min),max(Inflation.pred.max)));
lines(Inflation.pred.max,col="red");
lines(Inflation.pred.min,col="red");

plot.ts(Unemployment.predict$pred,ylim=c(min(Unemployment.pred.min),max(Unemployment.pred.max)));
lines(Unemployment.pred.max,col="red");
lines(Unemployment.pred.min,col="red");
```

